class Failure(Exception):
    def __init__(self, details):
        pass
